sudo: false
language: java
dist: trusty
arch:
  - amd64
  - ppc64le

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11

cache:
  directories:
    - .autoconf
    - "$HOME/.m2"

script:
  - mvn test jacoco:report

after_success:
  - mvn coveralls:report

notifications:
  email: false

# whitelist
branches:
  only:
    - master
    
jobs:
  exclude:
    - arch: ppc64le
      jdk: oraclejdk8
    - arch: ppc64le
      jdk: oraclejdk9
    
